### ISSUE TITLE
unused vias, shields

### ISSUE THREAD

**Issue by idank** [crehmann/TPS42#2]
Hey, thanks for opening the issue tracker! I'm looking into your keyboard, nice design.

I'd like to change it to use the integrated trackpoint pcb, and I was just studying your pcb and had these questions:

1. there are a lot of unused vias, what's up with that?
2. do i understand correctly that the lcd/oled shields exist solely to have the option to choose one or the other, while keeping the main pcb the same?

**Comment by crehmann** [comment]
Hi!
Thank you and I am happy to hear that it interests you.

1. Do you mean the vias that are connecting the ground fill? I used on the top and bottom side of the pcb a ground fill and added some vias to remove some islands 

2. yes, exactly!

**Comment by idank** [comment]
Ah interesting, thanks for answering. It took some time but I removed all of those and merged the OLED shield to the main pcb as I don't need the LCD one. Hope it all works out!

**Comment by crehmann** [comment]
You are welcome & happy build!

**Comment by idank** [comment]
Btw one issue I just noticed is that the diode direction isn't on the silk screen layers. I did my soldering with kicad open, but it might be good to fix that.

**Comment by crehmann** [comment]
There are different symbols for diodes and each has its own way to display the orientation. The one I used indicates the orientation with the closed side of the rectangle:

![image](https://github.com/crehmann/TPS42/assets/1273098/f05d7ac5-9a81-4036-a8be-1de5c46394a7)

**Comment by idank** [comment]
Ah, didn't notice those, thanks!

**Comment by crehmann** [comment]
No worries, let me know if you find any issues I can fix
