### ISSUE TITLE
I want to ues nice!nano to make the wireless version,how should I do?

### ISSUE THREAD

**Issue by Alohaq** [crehmann/TPS42#4]
I was immediately drawn to this keyboard, so I embarked on my first experience of building a ZMK keyboard. Initially, I tried to compile the tps42 keyboard configuration from the ARM folder, but it didn't work as expected. Then, I replaced the "arduino_pro_micro_pins.dtsi" file with the one from the "nicenano" folder. After that, I ran the command "west build -b tps42_left" and flashed the firmware. However, it seems that the keyboard is not functioning correctly.

**Comment by crehmann** [comment]
Hi,
Yes it is possible to use a nice!nano (I am using a nrfMicro). I used a custom ARM configuration to have custom code for the custom widgets. There you would also need to update the tps42-pinctrl.dtsi and tps42.dtsi.  A nice pinout can be found here to see which pins are different: https://github.com/joric/nrfmicro/wiki/Pinout

Another option would be to create a shield instead of an ARM board configuration. Creating a shield may be simpler and there is a documentation from ZMK: https://zmk.dev/docs/development/new-shield

**Comment by Alohaq** [comment]
Hi,
According to your instructions, I made changes to tps42.dtsi and tps42-pinctrl.dtsi. However, I have only implemented the left-hand side so far. Some keys are triggering incorrectly, and the bottom-left corner (identified as Caps Lock in the keymap) is not being triggered. I noticed a voltage drop of 1.9V across the diode at both ends. Additionally, when I measured the LCD side, the voltage was only around 0.4V. What could be causing these issues?

**Comment by Alohaq** [comment]
Just now, I changed the enable level of External VCC, and luckily, the LCD lit up successfully. Now, there are only two remaining issues: when pressing the Z key, sometimes it triggers the Windows key, and it happens quite frequently. I suspect there might be an issue with a certain diode. I'm getting closer to success. The other issue is that Caps Lock is not functioning.

**Comment by crehmann** [comment]
Do you use caps lock on a certain switch and is the switch not working in general or is it only the caps lock key?

**Comment by hunterwei** [comment]
> Hi, Yes it is possible to use a nice!nano (I am using a nrfMicro). I used a custom ARM configuration to have custom code for the custom widgets. There you would also need to update the tps42-pinctrl.dtsi and tps42.dtsi. A nice pinout can be found here to see which pins are different: https://github.com/joric/nrfmicro/wiki/Pinout
> 
> Another option would be to create a shield instead of an ARM board configuration. Creating a shield may be simpler and there is a documentation from ZMK: https://zmk.dev/docs/development/new-shield

I made a tps42-config repo that using the shield approach to support nice!nano MCU. For other TPS42 lovers' convenience, I list the link here, please feel free to use https://github.com/hunterwei/tps42-config

@crehmann, you can also close this issue if you like.

**Comment by crehmann** [comment]
@hunterwei Thank you for the config. I link to it in the wiki.
