### ISSUE TITLE
Rebasing on a recent qmk_firmware

### ISSUE THREAD

**Issue by daniel2887** [crehmann/TPS42#5]
Hi,

I just finished building a wired TPS42 and it seems to work well in testing (still waiting for keycaps). Thanks a ton for sharing your build, guide, and firmware.

I wanted to let you know that quite a bit has change on TOT qmk_firmware. If you're interested rebasing, I wanted to shared [this commit](https://github.com/qmk/qmk_firmware/commit/1d1c1b168091ff583a1614f59e55fec616aaaf92). Much of it was straightforward, except for the need to #define `PS2_MOUSE_USE_REMOTE_MODE`, which got me stumped for a few hours.

Hope this is useful, please feel free to close this issue either way.

**Comment by crehmann** [comment]
Hi, 

Thank you for the heads up regarding the firmware changes. I will look into it to rebase it. 

I am happy to hear from another build :) I would love to see another finished build :)
